

steps:
- id: docker-build
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker build -t $_GOOGLE_REGISTRY_URL/$_IMAGE_NAME:2.0.0 -t $_GOOGLE_REGISTRY_URL/$_IMAGE_NAME:1.0.0 . ']

substitutions:
  _GOOGLE_REGISTRY_URL: ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GOOGLE_REPOSITORY}
  _IMAGE_NAME: solitaire
  _GOOGLE_REPOSITORY: release
  _LOCATION: us-central1

images:
  - $_GOOGLE_REGISTRY_URL/$_IMAGE_NAME
